In [3]:
import pandas as pd

In [4]:
df= pd.read_csv("retail_store_sales.csv")

In [6]:
df["Date_raw"] = df["Transaction Date"]

df["Date"] = pd.to_datetime(df["Date_raw"], errors="coerce", dayfirst=True)

mask = df["Date"].isna()
df.loc[mask, "Date"] = pd.to_datetime(df.loc[mask, "Date_raw"], errors="coerce")

df["Date"] = df["Date"].dt.strftime("%d-%m-%Y")

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
 11  Date_raw          12575 non-null  str
 12  Date              12575 non-null  str
dtypes: float64(3), object(1), str(9)
memory usage: 1.2+ MB

In [8]:
df = df.drop("Transaction Date", axis=1)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Discount Applied  8376 non-null   object
 10  Date_raw          12575 non-null  str
 11  Date              12575 non-null  str
dtypes: float64(3), object(1), str(8)
memory usage: 1.2+ MB

In [10]:
df = df.drop("Date_raw", axis=1)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Discount Applied  8376 non-null   object
 10  Date              12575 non-null  str
dtypes: float64(3), object(1), str(7)
memory usage: 1.1+ MB

In [12]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce", dayfirst=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Discount Applied  8376 non-null   object
 10  Date              12575 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), object(1), str(6)
memory usage: 1.1+ MB

In [14]:
df["Day_Name"] = df["Date"].dt.day_name()
df["Month"] = df["Date"].dt.month_name()

In [15]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Discount Applied,Date,Day_Name,Month
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,True,2024-08-04,Sunday,August
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,True,2023-07-23,Sunday,July
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,False,2022-05-10,Tuesday,May
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,NaN,2022-07-05,Tuesday,July
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,False,2022-02-10,Thursday,February

In [25]:
months = ["", "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December"]

In [30]:
df["Monthaa"] = df["Date"].dt.month_name()

In [31]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Discount Applied,Date,Day_Name,Month,Monthaa
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,True,2024-08-04,Sunday,August,August
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,True,2023-07-23,Sunday,July,July
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,False,2022-05-10,Tuesday,May,May
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,NaN,2022-07-05,Tuesday,July,July
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,False,2022-02-10,Thursday,February,February

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Discount Applied  8376 non-null   object
 10  Date              12575 non-null  datetime64[us]
 11  Day_Name          12575 non-null  str
 12  Month             12575 non-null  str
dtypes: datetime64[us](1), float64(3), object(1), str(8)
memory usage: 1.2+ MB